repositories:
- name: sandbox
  url: https://ryodocx.github.io/k8s-sandbox
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: pipecd
  url: https://charts.pipecd.dev

environments:
  default: {}

templates:
  default: &default
    values:
      - helmfile-config/values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
      - helmfile-config/secrets/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
  pipecd: &pipecd
    <<: *default
    namespace: pipecd

releases:
# PipeCD
- name: pipecd-control-plane
  <<: *pipecd
  chart: pipecd/pipecd
  version: v0.9.11
  needs: 
    - pipecd/pipecd-mysql
  installed: false

- name: pipecd-mysql
  <<: *pipecd
  chart: bitnami/mariadb
  version: 9.3.8
