repositories:
- name: sandbox
  url: https://ryodocx.github.io/k8s-sandbox
- name: bitnami
  url: https://charts.bitnami.com/bitnami

environments:
  default: {}

templates:
  default: &default
    values:
      - helmfile-config/values/{{`{{ .Release.Name }}`}}-{{`{{ .Environment.Name }}`}}.yaml
    secrets:
      - helmfile-config/secrets/{{`{{ .Release.Name }}`}}-{{`{{ .Environment.Name }}`}}.yaml
  argo: &argo-rollouts
    # <<: *default
    namespace: argo-rollouts

releases:
# Argo Workflows
# Argo CD

# Argo Rollouts
- name: argo-rollouts
  <<: *argo-rollouts
  chart: ./kustomize/argo-rollouts

- name: argo-rollouts-demo
  <<: *argo-rollouts
  namespace: argo-rollouts
  chart: ./kustomize/argo-rollouts-demo
  needs: 
    - argo-rollouts/argo-rollouts

- name: pipecd-ingress
  <<: *argo-rollouts
  chart: sandbox/ingress
  version: 0.1.0
  needs:
    - argo-rollouts/argo-rollouts-demo
  values:
  - items:
    - name: argo-rollouts-demo
      ingress:
        host: argo-rollouts-demo.internal.ryodocx.net
      target:
        serviceName: rollouts-demo
        port: 80
    - name: argo-rollouts-demo-public
      ingress:
        host: argo-rollouts-demo.ryodocx.net
        annotations:
          external-dns.alpha.kubernetes.io/target: "public.ryodocx.net"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          kubernetes.io/ingress.class: ""
      target:
        serviceName: rollouts-demo
        port: 80

# Argo Events
