repositories:
- name: sandbox
  url: https://ryodocx.github.io/k8s-sandbox
- name: bitnami
  url: https://charts.bitnami.com/bitnami

environments:
  default: {}

templates:
  default: &default
    values:
      - helmfile-config/values/{{`{{ .Release.Name }}`}}-{{`{{ .Environment.Name }}`}}.yaml
    secrets:
      - helmfile-config/secrets/{{`{{ .Release.Name }}`}}-{{`{{ .Environment.Name }}`}}.yaml
  argo: &argo
    <<: *default
    namespace: argo

releases:
# Argo Workflows
# Argo CD

# Argo Rollouts
- name: argo-rollouts
  # <<: *default
  namespace: argo-rollouts-test
  chart: ./kustomize/argo-rollouts

# Argo Events
