apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
              readOnly: true
          livenessProbe: &probe
            httpGet:
              path: /
              port: http
          readinessProbe: *probe
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "3s"]
      volumes:
      - name: html
        configMap:
          name: {{ include "fullname" . }}
          items:
            - key: index.html
              path: index.html
