items:
  - name: pipecd
    ingress:
      host: pipecd.internal.ryodocx.net
      annotations: {}
    target:
      serviceName: pipecd-control-plane
      port: 8080
  - name: pipecd-ops
    ingress:
      host: pipecd-ops.internal.ryodocx.net
      annotations: {}
    target:
      serviceName: pipecd-control-plane-ops
      port: 9082
