apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "simple-deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "simple-deployment.selectorLabels" . | nindent 8 }}
    annotations:
      checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      volumes:
      - name: html
        configMap:
          name: {{ include "fullname" . }}
