apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "simple-deployment.fullname" . }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "simple-deployment.fullname" . }}
                port:
                  name: http
