apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector: {{- include "selectorLabels" . | nindent 4 }}
